<a href="https://colab.research.google.com/github/TofuNorthLynX/main/blob/main/reuters.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [93]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [67]:
df = pd.read_csv('bbc-news-data.csv', sep = '\t')
df

,category,filename,title,content
0,business,001.txt,Ad sales boost Time Warner profit,Quarterly profits at US media giant TimeWarne...
1,business,002.txt,Dollar gains on Greenspan speech,The dollar has hit its highest level against ...
2,business,003.txt,Yukos unit buyer faces loan claim,The owners of embattled Russian oil giant Yuk...
3,business,004.txt,High fuel prices hit BA's profits,British Airways has blamed high fuel prices f...
4,business,005.txt,Pernod takeover talk lifts Domecq,Shares in UK drinks and food firm Allied Dome...
...,...,...,...,...
2220,tech,397.txt,BT program to beat dialler scams,BT is introducing two initiatives to help bea...
2221,tech,398.txt,Spam e-mails tempt net shoppers,Computer users across the world continue to i...
2222,tech,399.txt,Be careful how you code,A new European directive could put software w...
2223,tech,400.txt,US cyber security chief resigns,The man making sure US computer networks are ...
2224,tech,401.txt,Losing yourself in online gaming,"Online role playing games are time-consuming,..."

In [68]:
df.title = df.title.str.lower()
df.content = df.content.str.lower()

In [69]:
df

,category,filename,title,content
0,business,001.txt,ad sales boost time warner profit,quarterly profits at us media giant timewarne...
1,business,002.txt,dollar gains on greenspan speech,the dollar has hit its highest level against ...
2,business,003.txt,yukos unit buyer faces loan claim,the owners of embattled russian oil giant yuk...
3,business,004.txt,high fuel prices hit ba's profits,british airways has blamed high fuel prices f...
4,business,005.txt,pernod takeover talk lifts domecq,shares in uk drinks and food firm allied dome...
...,...,...,...,...
2220,tech,397.txt,bt program to beat dialler scams,bt is introducing two initiatives to help bea...
2221,tech,398.txt,spam e-mails tempt net shoppers,computer users across the world continue to i...
2222,tech,399.txt,be careful how you code,a new european directive could put software w...
2223,tech,400.txt,us cyber security chief resigns,the man making sure us computer networks are ...
2224,tech,401.txt,losing yourself in online gaming,"online role playing games are time-consuming,..."

In [70]:
df.title = df.title.replace('[<>/.,?!+(=)-_*©:;"|]', '', regex=True)
df.content = df.content.replace('[<>/.,?!+(=)-_*©:;"|]', '', regex=True)
df

,category,filename,title,content
0,business,001.txt,ad sales boost time warner profit,quarterly profits at us media giant timewarne...
1,business,002.txt,dollar gains on greenspan speech,the dollar has hit its highest level against ...
2,business,003.txt,yukos unit buyer faces loan claim,the owners of embattled russian oil giant yuk...
3,business,004.txt,high fuel prices hit ba's profits,british airways has blamed high fuel prices f...
4,business,005.txt,pernod takeover talk lifts domecq,shares in uk drinks and food firm allied dome...
...,...,...,...,...
2220,tech,397.txt,bt program to beat dialler scams,bt is introducing two initiatives to help bea...
2221,tech,398.txt,spam emails tempt net shoppers,computer users across the world continue to i...
2222,tech,399.txt,be careful how you code,a new european directive could put software w...
2223,tech,400.txt,us cyber security chief resigns,the man making sure us computer networks are ...
2224,tech,401.txt,losing yourself in online gaming,online role playing games are timeconsuming b...

In [71]:
df = df.drop('filename', axis=1)

In [72]:
df.head(10)

,category,title,content
0,business,ad sales boost time warner profit,quarterly profits at us media giant timewarne...
1,business,dollar gains on greenspan speech,the dollar has hit its highest level against ...
2,business,yukos unit buyer faces loan claim,the owners of embattled russian oil giant yuk...
3,business,high fuel prices hit ba's profits,british airways has blamed high fuel prices f...
4,business,pernod takeover talk lifts domecq,shares in uk drinks and food firm allied dome...
5,business,japan narrowly escapes recession,japan's economy teetered on the brink of a te...
6,business,jobs growth still slow in the us,the us created fewer jobs than expected in ja...
7,business,india calls for fair trade rules,india which attends the g meeting of seven le...
8,business,ethiopia's crop production up %,ethiopia produced million tonnes of crops in...
9,business,court rejects $bn tobacco case,a us government claim accusing the country's ...

In [73]:
with open('stopwords.txt', 'r') as f:
    stopw = [line.strip() for line in f]

In [74]:
from nltk.tokenize import word_tokenize
import nltk

nltk.download('punkt')

tokens = []
stopwords_cleaned = []

for text in df['content']:
  text = word_tokenize(text)
  tokens.append(text)
  text = [word for word in text if word not in stopw]
  stopwords_cleaned.append(text)

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [75]:
df['content'] = stopwords_cleaned
df

,category,title,content
0,business,ad sales boost time warner profit,"[quarterly, profits, media, giant, timewarner,..."
1,business,dollar gains on greenspan speech,"[dollar, hit, highest, level, euro, months, fe..."
2,business,yukos unit buyer faces loan claim,"[owners, embattled, russian, oil, giant, yukos..."
3,business,high fuel prices hit ba's profits,"[british, airways, blamed, high, fuel, prices,..."
4,business,pernod takeover talk lifts domecq,"[shares, uk, drinks, food, firm, allied, domec..."
...,...,...,...
2220,tech,bt program to beat dialler scams,"[bt, introducing, initiatives, beat, rogue, di..."
2221,tech,spam emails tempt net shoppers,"[computer, users, world, continue, ignore, sec..."
2222,tech,be careful how you code,"[european, directive, put, software, writers, ..."
2223,tech,us cyber security chief resigns,"[man, making, computer, networks, safe, secure..."
2224,tech,losing yourself in online gaming,"[online, role, playing, games, timeconsuming, ..."

In [76]:
from sklearn.model_selection import train_test_split
y = df.category
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [77]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(max_iter = 50000, random_state = 0).fit(X_train, y_train)

In [78]:
x_predict = clf.predict(X_test)

In [79]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, x_predict))

0.9687074829931973

In [95]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

gbc = GradientBoostingClassifier(random_state=0)
gbc.fit(X_train, y_train)

y_pred = gbc.predict(X_test)

print(accuracy_score(y_test, y_pred))

0.9483146067415731

In [94]:
from sklearn.model_selection import validation_curve
from sklearn.ensemble import GradientBoostingClassifier

# Создаем модель
model = GradientBoostingClassifier()

# Создаем сетку параметров
param_range = np.arange(1, 100, 10)
train_scores, test_scores = validation_curve(
    model, X, y, param_name="n_estimators", param_range=param_range,
    cv=5, scoring="accuracy", n_jobs=-1)

# Вычисляем среднее значение и стандартное отклонение для оценок на обучающем и тестовом наборах
train_mean = np.mean(train_scores, axis=1)
train_std = np.std(train_scores, axis=1)
test_mean = np.mean(test_scores, axis=1)
test_std = np.std(test_scores, axis=1)

# Строим график
plt.title("Validation Curve with GradientBoostingClassifier")
plt.xlabel("n_estimators")
plt.ylabel("Score")
plt.ylim(0.0, 1.1)
plt.xticks(param_range)
lw = 2
plt.plot(param_range, train_mean, label="Training score",
             color="darkorange", lw=lw)
plt.fill_between(param_range, train_mean - train_std,
                 train_mean + train_std, alpha=0.2,
                 color="darkorange", lw=lw)
plt.plot(param_range, test_mean, label="Cross-validation score",
             color="navy", lw=lw)
plt.fill_between(param_range, test_mean - test_std,
                 test_mean + test_std, alpha=0.2,
                 color="navy", lw=lw)
plt.legend(loc="best")
plt.show()

KeyboardInterrupt: ignored